kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol-ml-prefect
  namespace: default
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G