apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-applications
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["applications"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]        
