apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins 
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Force=true,Replace=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    managedNamespaceMetadata:
      annotations: 
        name: jenkins
        type: cicd
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - Retry=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  sources:
  - repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.17
    helm:
      valueFiles:
      - $values/deployment/dev/jenkins/jenkins-values.yaml
  - repoURL: 'https://github.com/JBris/kubernetes-kind-examples.git'
    targetRevision: main
    ref: values

