apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      protocol: TCP